#!/usr/bin/env bash
# configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
apt-get update
apt-get install nginx -y
ufw allow "Nginx HTTP"
echo "Holberton School for the win" > /var/www/html/index.html
echo "Ceci n' est pas une page" > /var/www/html/404.html
sed -i "/listen 80 default_server/a error_page 404 /404.html;" /etc/nginx/sites-available/default
service nginx restart
