#!/usr/bin/env bash
#Install your load balancer 
sudo apt-get update
sudo apt-get -y install haproxy
sudo sed -i '$ a\\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 1854-web-01 34.75.217.72:80\n\tserver 1854-web-02 34.73.33.136:80' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
