#!/usr/bin/env bash
# shows the listener ports and also shows the PID and the name of the program to which each connector belongs
if(($# == 1))
then
    ping $1
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
