#!/usr/bin/env bash
# script 101-manage_my_process that manages manage_my_process.
TEMP_FILE=/var/run/holbertonscript.pid
string="manage_my_process started"
if [ "$1" = "start" ]
then
    ./manage_my_process &
    pidof -s bash > "$TEMP_FILE"
    echo "$string started"
elif [ "$1" = stop ]
then
    kill "$(cat $TEMP_FILE)"
    rm "$TEMP_FILE" 
    echo "$string stopped"
elif [ "$1" = restart ]
then
    kill "$(cat $TEMP_FILE)"
    rm "$TEMP_FILE"
    ./manage_my_process &
    pidof -s bash > "$TEMP_FILE"
    echo "$string started" 
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi