#!/usr/bin/env bash
#This script is displaying "Holberton School" 10 times
# ----------------------------
string="Holberton School"
for i in 1 2 3 4 5 6 7 8 9 10; do
    echo $string
done
# ----------------------------