#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd.
# username
# user id
# Home directory path for the user
file="/etc/passwd"
while read -r f
do
    echo "$f" | cut -d':' -f1,3,6
done < "$file"