#!/usr/bin/env bash
# script that displays Holberton School 10 times,
# but for the 9th iteration, displays Holberton School
# and then Hi on a new line.
string="Holberton School"
i=0
while [ $i -lt 11 ]
do 
    if(( i==9 ))
    then
        echo "Hi"
    else
        echo "$string"
    fi
    i=$((i+1))
done