#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
j=0
while [ $j -lt 13 ]; do
    if((j == j))
    then
        echo "Hour: $j"
        i=1
        while [ $i -lt 60 ]; do
            echo "$i"
        i=$((i+1))
        done
    fi
    j=$((j+1))
done