#!/usr/bin/env bash
# change host file 
cp /etc/hosts ~/hosts.new
sed -i.bak '127.0.0.1/127.0.0.2' ~/hosts.new
sed -i.bak '/localhost/ a 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
