#!/usr/bin/env bash
# In this first debugging project, you will need to get Apache to run on the container and to
# return a page containing Hello Holberton when querying the root of it
apt-get update &&
apt-get install -y apache2
echo "ServerName localhost" >> /etc/apache2/apache2.conf
service apache2 start
